# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ 'master' ,'main']

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set Spark env
      run: |
        export SPARK_LOCAL_IP=127.0.0.1
        export SPARK_SUBMIT_OPTS="--illegal-access=permit -Dio.netty.tryReflectionSetAccessible=true"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest wheel
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate coverage report
      run: |
        coverage run -m pytest tests/test_*.py
        coverage xml
        
    - name: Publish test coverage
      uses: codecov/codecov-action@v2

    - name: Build
      run: |
        python setup.py bdist_wheel --universal

    - uses: actions/upload-artifact@v2
      with:
        name: dbignite-0.1-py2.py3-none-any.whl
        path: dist/dbignite-0.1-py2.py3-none-any.whl